//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:11</p>
  /// </summary>
  public class RobustYamlModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<RobustFieldQuery, List<RobustDataField>> TypeFields => _TypeFields;
    
    //private fields
    [NotNull] private readonly RdCall<RobustFieldQuery, List<RobustDataField>> _TypeFields;
    
    //primary constructor
    private RobustYamlModel(
      [NotNull] RdCall<RobustFieldQuery, List<RobustDataField>> typeFields
    )
    {
      if (typeFields == null) throw new ArgumentNullException("typeFields");
      
      _TypeFields = typeFields;
      BindableChildren.Add(new KeyValuePair<string, object>("typeFields", _TypeFields));
    }
    //secondary constructor
    internal RobustYamlModel (
    ) : this (
      new RdCall<RobustFieldQuery, List<RobustDataField>>(RobustFieldQuery.Read, RobustFieldQuery.Write, ReadRobustDataFieldList, WriteRobustDataFieldList)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<List<RobustDataField>> ReadRobustDataFieldList = RobustDataField.Read.List();
    
    public static  CtxWriteDelegate<List<RobustDataField>> WriteRobustDataFieldList = RobustDataField.Write.List();
    
    protected override long SerializationHash => -5474492741890904948L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RobustYamlModel (");
      using (printer.IndentCookie()) {
        printer.Print("typeFields = "); _TypeFields.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionRobustYamlModelEx
   {
    public static RobustYamlModel GetRobustYamlModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("robustYamlModel", () => new RobustYamlModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:13</p>
  /// </summary>
  public sealed class RobustDataField : IPrintable, IEquatable<RobustDataField>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string Type {get; private set;}
    [CanBeNull] public string Summary {get; private set;}
    [CanBeNull] public string PrototypeKind {get; private set;}
    
    //private fields
    //primary constructor
    public RobustDataField(
      [NotNull] string name,
      [NotNull] string type,
      [CanBeNull] string summary,
      [CanBeNull] string prototypeKind
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (type == null) throw new ArgumentNullException("type");
      
      Name = name;
      Type = type;
      Summary = summary;
      PrototypeKind = prototypeKind;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string type, [CanBeNull] out string summary, [CanBeNull] out string prototypeKind)
    {
      name = Name;
      type = Type;
      summary = Summary;
      prototypeKind = PrototypeKind;
    }
    //statics
    
    public static CtxReadDelegate<RobustDataField> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var type = reader.ReadString();
      var summary = ReadStringNullable(ctx, reader);
      var prototypeKind = ReadStringNullable(ctx, reader);
      var _result = new RobustDataField(name, type, summary, prototypeKind);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<RobustDataField> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.Type);
      WriteStringNullable(ctx, writer, value.Summary);
      WriteStringNullable(ctx, writer, value.PrototypeKind);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RobustDataField) obj);
    }
    public bool Equals(RobustDataField other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && Type == other.Type && Equals(Summary, other.Summary) && Equals(PrototypeKind, other.PrototypeKind);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + Type.GetHashCode();
        hash = hash * 31 + (Summary != null ? Summary.GetHashCode() : 0);
        hash = hash * 31 + (PrototypeKind != null ? PrototypeKind.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RobustDataField (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("type = "); Type.PrintEx(printer); printer.Println();
        printer.Print("summary = "); Summary.PrintEx(printer); printer.Println();
        printer.Print("prototypeKind = "); PrototypeKind.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:20</p>
  /// </summary>
  public sealed class RobustFieldQuery : IPrintable, IEquatable<RobustFieldQuery>
  {
    //fields
    //public fields
    [NotNull] public string ClassName {get; private set;}
    [NotNull] public List<string> Path {get; private set;}
    
    //private fields
    //primary constructor
    public RobustFieldQuery(
      [NotNull] string className,
      [NotNull] List<string> path
    )
    {
      if (className == null) throw new ArgumentNullException("className");
      if (path == null) throw new ArgumentNullException("path");
      
      ClassName = className;
      Path = path;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string className, [NotNull] out List<string> path)
    {
      className = ClassName;
      path = Path;
    }
    //statics
    
    public static CtxReadDelegate<RobustFieldQuery> Read = (ctx, reader) => 
    {
      var className = reader.ReadString();
      var path = ReadStringList(ctx, reader);
      var _result = new RobustFieldQuery(className, path);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RobustFieldQuery> Write = (ctx, writer, value) => 
    {
      writer.Write(value.ClassName);
      WriteStringList(ctx, writer, value.Path);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RobustFieldQuery) obj);
    }
    public bool Equals(RobustFieldQuery other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ClassName == other.ClassName && Path.SequenceEqual(other.Path);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + ClassName.GetHashCode();
        hash = hash * 31 + Path.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RobustFieldQuery (");
      using (printer.IndentCookie()) {
        printer.Print("className = "); ClassName.PrintEx(printer); printer.Println();
        printer.Print("path = "); Path.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
