//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:11</p>
  /// </summary>
  public class RobustYamlModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<RobustFieldQuery, RobustFieldsReply> TypeFields => _TypeFields;
    [NotNull] public IRdEndpoint<RobustFieldQuery, RobustImplementationsReply> TypeImplementations => _TypeImplementations;
    
    //private fields
    [NotNull] private readonly RdCall<RobustFieldQuery, RobustFieldsReply> _TypeFields;
    [NotNull] private readonly RdCall<RobustFieldQuery, RobustImplementationsReply> _TypeImplementations;
    
    //primary constructor
    private RobustYamlModel(
      [NotNull] RdCall<RobustFieldQuery, RobustFieldsReply> typeFields,
      [NotNull] RdCall<RobustFieldQuery, RobustImplementationsReply> typeImplementations
    )
    {
      if (typeFields == null) throw new ArgumentNullException("typeFields");
      if (typeImplementations == null) throw new ArgumentNullException("typeImplementations");
      
      _TypeFields = typeFields;
      _TypeImplementations = typeImplementations;
      BindableChildren.Add(new KeyValuePair<string, object>("typeFields", _TypeFields));
      BindableChildren.Add(new KeyValuePair<string, object>("typeImplementations", _TypeImplementations));
    }
    //secondary constructor
    internal RobustYamlModel (
    ) : this (
      new RdCall<RobustFieldQuery, RobustFieldsReply>(RobustFieldQuery.Read, RobustFieldQuery.Write, RobustFieldsReply.Read, RobustFieldsReply.Write),
      new RdCall<RobustFieldQuery, RobustImplementationsReply>(RobustFieldQuery.Read, RobustFieldQuery.Write, RobustImplementationsReply.Read, RobustImplementationsReply.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 1058776472414428381L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RobustYamlModel (");
      using (printer.IndentCookie()) {
        printer.Print("typeFields = "); _TypeFields.PrintEx(printer); printer.Println();
        printer.Print("typeImplementations = "); _TypeImplementations.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionRobustYamlModelEx
   {
    public static RobustYamlModel GetRobustYamlModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("robustYamlModel", () => new RobustYamlModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:13</p>
  /// </summary>
  public sealed class RobustDataField : IPrintable, IEquatable<RobustDataField>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string Type {get; private set;}
    [CanBeNull] public string Summary {get; private set;}
    [CanBeNull] public string PrototypeKind {get; private set;}
    [CanBeNull] public string KeyPrototypeKind {get; private set;}
    public bool Dictionary {get; private set;}
    public bool Sequence {get; private set;}
    public bool CustomSerializer {get; private set;}
    public bool Localized {get; private set;}
    public bool Polymorphic {get; private set;}
    [NotNull] public List<string> Values {get; private set;}
    [NotNull] public List<string> KeyValues {get; private set;}
    
    //private fields
    //primary constructor
    public RobustDataField(
      [NotNull] string name,
      [NotNull] string type,
      [CanBeNull] string summary,
      [CanBeNull] string prototypeKind,
      [CanBeNull] string keyPrototypeKind,
      bool dictionary,
      bool sequence,
      bool customSerializer,
      bool localized,
      bool polymorphic,
      [NotNull] List<string> values,
      [NotNull] List<string> keyValues
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (type == null) throw new ArgumentNullException("type");
      if (values == null) throw new ArgumentNullException("values");
      if (keyValues == null) throw new ArgumentNullException("keyValues");
      
      Name = name;
      Type = type;
      Summary = summary;
      PrototypeKind = prototypeKind;
      KeyPrototypeKind = keyPrototypeKind;
      Dictionary = dictionary;
      Sequence = sequence;
      CustomSerializer = customSerializer;
      Localized = localized;
      Polymorphic = polymorphic;
      Values = values;
      KeyValues = keyValues;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string type, [CanBeNull] out string summary, [CanBeNull] out string prototypeKind, [CanBeNull] out string keyPrototypeKind, out bool dictionary, out bool sequence, out bool customSerializer, out bool localized, out bool polymorphic, [NotNull] out List<string> values, [NotNull] out List<string> keyValues)
    {
      name = Name;
      type = Type;
      summary = Summary;
      prototypeKind = PrototypeKind;
      keyPrototypeKind = KeyPrototypeKind;
      dictionary = Dictionary;
      sequence = Sequence;
      customSerializer = CustomSerializer;
      localized = Localized;
      polymorphic = Polymorphic;
      values = Values;
      keyValues = KeyValues;
    }
    //statics
    
    public static CtxReadDelegate<RobustDataField> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var type = reader.ReadString();
      var summary = ReadStringNullable(ctx, reader);
      var prototypeKind = ReadStringNullable(ctx, reader);
      var keyPrototypeKind = ReadStringNullable(ctx, reader);
      var dictionary = reader.ReadBool();
      var sequence = reader.ReadBool();
      var customSerializer = reader.ReadBool();
      var localized = reader.ReadBool();
      var polymorphic = reader.ReadBool();
      var values = ReadStringList(ctx, reader);
      var keyValues = ReadStringList(ctx, reader);
      var _result = new RobustDataField(name, type, summary, prototypeKind, keyPrototypeKind, dictionary, sequence, customSerializer, localized, polymorphic, values, keyValues);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RobustDataField> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.Type);
      WriteStringNullable(ctx, writer, value.Summary);
      WriteStringNullable(ctx, writer, value.PrototypeKind);
      WriteStringNullable(ctx, writer, value.KeyPrototypeKind);
      writer.Write(value.Dictionary);
      writer.Write(value.Sequence);
      writer.Write(value.CustomSerializer);
      writer.Write(value.Localized);
      writer.Write(value.Polymorphic);
      WriteStringList(ctx, writer, value.Values);
      WriteStringList(ctx, writer, value.KeyValues);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RobustDataField) obj);
    }
    public bool Equals(RobustDataField other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && Type == other.Type && Equals(Summary, other.Summary) && Equals(PrototypeKind, other.PrototypeKind) && Equals(KeyPrototypeKind, other.KeyPrototypeKind) && Dictionary == other.Dictionary && Sequence == other.Sequence && CustomSerializer == other.CustomSerializer && Localized == other.Localized && Polymorphic == other.Polymorphic && Values.SequenceEqual(other.Values) && KeyValues.SequenceEqual(other.KeyValues);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + Type.GetHashCode();
        hash = hash * 31 + (Summary != null ? Summary.GetHashCode() : 0);
        hash = hash * 31 + (PrototypeKind != null ? PrototypeKind.GetHashCode() : 0);
        hash = hash * 31 + (KeyPrototypeKind != null ? KeyPrototypeKind.GetHashCode() : 0);
        hash = hash * 31 + Dictionary.GetHashCode();
        hash = hash * 31 + Sequence.GetHashCode();
        hash = hash * 31 + CustomSerializer.GetHashCode();
        hash = hash * 31 + Localized.GetHashCode();
        hash = hash * 31 + Polymorphic.GetHashCode();
        hash = hash * 31 + Values.ContentHashCode();
        hash = hash * 31 + KeyValues.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RobustDataField (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("type = "); Type.PrintEx(printer); printer.Println();
        printer.Print("summary = "); Summary.PrintEx(printer); printer.Println();
        printer.Print("prototypeKind = "); PrototypeKind.PrintEx(printer); printer.Println();
        printer.Print("keyPrototypeKind = "); KeyPrototypeKind.PrintEx(printer); printer.Println();
        printer.Print("dictionary = "); Dictionary.PrintEx(printer); printer.Println();
        printer.Print("sequence = "); Sequence.PrintEx(printer); printer.Println();
        printer.Print("customSerializer = "); CustomSerializer.PrintEx(printer); printer.Println();
        printer.Print("localized = "); Localized.PrintEx(printer); printer.Println();
        printer.Print("polymorphic = "); Polymorphic.PrintEx(printer); printer.Println();
        printer.Print("values = "); Values.PrintEx(printer); printer.Println();
        printer.Print("keyValues = "); KeyValues.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:28</p>
  /// </summary>
  public sealed class RobustFieldQuery : IPrintable, IEquatable<RobustFieldQuery>
  {
    //fields
    //public fields
    [NotNull] public string ClassName {get; private set;}
    [NotNull] public List<string> Path {get; private set;}
    
    //private fields
    //primary constructor
    public RobustFieldQuery(
      [NotNull] string className,
      [NotNull] List<string> path
    )
    {
      if (className == null) throw new ArgumentNullException("className");
      if (path == null) throw new ArgumentNullException("path");
      
      ClassName = className;
      Path = path;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string className, [NotNull] out List<string> path)
    {
      className = ClassName;
      path = Path;
    }
    //statics
    
    public static CtxReadDelegate<RobustFieldQuery> Read = (ctx, reader) => 
    {
      var className = reader.ReadString();
      var path = ReadStringList(ctx, reader);
      var _result = new RobustFieldQuery(className, path);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RobustFieldQuery> Write = (ctx, writer, value) => 
    {
      writer.Write(value.ClassName);
      WriteStringList(ctx, writer, value.Path);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RobustFieldQuery) obj);
    }
    public bool Equals(RobustFieldQuery other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ClassName == other.ClassName && Path.SequenceEqual(other.Path);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + ClassName.GetHashCode();
        hash = hash * 31 + Path.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RobustFieldQuery (");
      using (printer.IndentCookie()) {
        printer.Print("className = "); ClassName.PrintEx(printer); printer.Println();
        printer.Print("path = "); Path.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:33</p>
  /// </summary>
  public sealed class RobustFieldsReply : IPrintable, IEquatable<RobustFieldsReply>
  {
    //fields
    //public fields
    public bool Resolved {get; private set;}
    [NotNull] public List<RobustDataField> Fields {get; private set;}
    
    //private fields
    //primary constructor
    public RobustFieldsReply(
      bool resolved,
      [NotNull] List<RobustDataField> fields
    )
    {
      if (fields == null) throw new ArgumentNullException("fields");
      
      Resolved = resolved;
      Fields = fields;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool resolved, [NotNull] out List<RobustDataField> fields)
    {
      resolved = Resolved;
      fields = Fields;
    }
    //statics
    
    public static CtxReadDelegate<RobustFieldsReply> Read = (ctx, reader) => 
    {
      var resolved = reader.ReadBool();
      var fields = ReadRobustDataFieldList(ctx, reader);
      var _result = new RobustFieldsReply(resolved, fields);
      return _result;
    };
    public static CtxReadDelegate<List<RobustDataField>> ReadRobustDataFieldList = RobustDataField.Read.List();
    
    public static CtxWriteDelegate<RobustFieldsReply> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Resolved);
      WriteRobustDataFieldList(ctx, writer, value.Fields);
    };
    public static  CtxWriteDelegate<List<RobustDataField>> WriteRobustDataFieldList = RobustDataField.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RobustFieldsReply) obj);
    }
    public bool Equals(RobustFieldsReply other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Resolved == other.Resolved && Fields.SequenceEqual(other.Fields);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Resolved.GetHashCode();
        hash = hash * 31 + Fields.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RobustFieldsReply (");
      using (printer.IndentCookie()) {
        printer.Print("resolved = "); Resolved.PrintEx(printer); printer.Println();
        printer.Print("fields = "); Fields.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RobustYamlModel.kt:38</p>
  /// </summary>
  public sealed class RobustImplementationsReply : IPrintable, IEquatable<RobustImplementationsReply>
  {
    //fields
    //public fields
    public bool Resolved {get; private set;}
    [NotNull] public List<string> Names {get; private set;}
    
    //private fields
    //primary constructor
    public RobustImplementationsReply(
      bool resolved,
      [NotNull] List<string> names
    )
    {
      if (names == null) throw new ArgumentNullException("names");
      
      Resolved = resolved;
      Names = names;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool resolved, [NotNull] out List<string> names)
    {
      resolved = Resolved;
      names = Names;
    }
    //statics
    
    public static CtxReadDelegate<RobustImplementationsReply> Read = (ctx, reader) => 
    {
      var resolved = reader.ReadBool();
      var names = ReadStringList(ctx, reader);
      var _result = new RobustImplementationsReply(resolved, names);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RobustImplementationsReply> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Resolved);
      WriteStringList(ctx, writer, value.Names);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RobustImplementationsReply) obj);
    }
    public bool Equals(RobustImplementationsReply other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Resolved == other.Resolved && Names.SequenceEqual(other.Names);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Resolved.GetHashCode();
        hash = hash * 31 + Names.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RobustImplementationsReply (");
      using (printer.IndentCookie()) {
        printer.Print("resolved = "); Resolved.PrintEx(printer); printer.Println();
        printer.Print("names = "); Names.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
